import { Exercise } from "./types";

export const EXERCISES: Exercise[] = [
  // Original 12 exercises
  {
    id: "push-up",
    name: "푸시업",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["가슴", "삼두근", "어깨"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "상체 근력을 키우는 기본 운동입니다.",
    instructions: ["손을 어깨 너비로 벌리고 엎드립니다", "몸을 일직선으로 유지합니다", "팔꿈치를 구부려 가슴이 바닥에 닿을 때까지 내려갑니다", "팔을 펴서 시작 자세로 돌아옵니다"],
    calories: 8,
    youtubeVideoId: "IODxDxX7oi4",
  },
  {
    id: "squat",
    name: "스쿼트",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["대퇴사두근", "둔근", "햄스트링"],
    sets: 3,
    reps: 15,
    restTime: 60,
    description: "하체 전체를 강화하는 핵심 운동입니다.",
    instructions: ["발을 어깨 너비로 벌리고 섭니다", "등을 곧게 펴고 가슴을 들어올립니다", "무릎이 발끝을 넘지 않도록 앉습니다", "허벅지가 바닥과 평행이 될 때까지 내려갑니다", "발뒤꿈치로 밀어 일어납니다"],
    calories: 10,
    youtubeVideoId: "aclHkVaku9U",
  },
  {
    id: "deadlift",
    name: "데드리프트",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["등", "햄스트링", "둔근", "코어"],
    sets: 4,
    reps: 6,
    restTime: 120,
    description: "전신을 강화하는 복합 운동입니다.",
    instructions: ["바벨 앞에 서서 발을 어깨 너비로 벌립니다", "등을 곧게 펴고 바벨을 잡습니다", "다리와 등의 힘으로 바벨을 들어올립니다", "천천히 내립니다"],
    calories: 14,
    youtubeVideoId: "r4MzxtBKyNE",
  },
  {
    id: "plank",
    name: "플랭크",
    category: "core",
    difficulty: "beginner",
    muscleGroups: ["코어", "어깨"],
    sets: 3,
    reps: 1,
    duration: 30,
    restTime: 30,
    description: "코어를 강화하는 정적 운동입니다.",
    instructions: ["팔꿈치를 어깨 아래에 놓고 엎드립니다", "몸을 일직선으로 유지합니다", "시간을 유지합니다"],
    calories: 6,
    youtubeVideoId: "pSHjTRCQxIw",
  },
  {
    id: "burpee",
    name: "버피",
    category: "cardio",
    difficulty: "intermediate",
    muscleGroups: ["전신"],
    sets: 3,
    reps: 10,
    restTime: 60,
    description: "전신을 단련하는 고강도 운동입니다.",
    instructions: ["서있는 자세에서 시작합니다", "쪼그려 앉아 손을 바닥에 놓습니다", "다리를 뒤로 펴서 푸시업 자세를 만듭니다", "다리를 다시 가져와 일어섭니다"],
    calories: 12,
    youtubeVideoId: "4IdetMi7v4w",
  },
  {
    id: "mountain-climber",
    name: "마운틴 클라이머",
    category: "cardio",
    difficulty: "intermediate",
    muscleGroups: ["코어", "가슴", "다리"],
    sets: 3,
    reps: 20,
    restTime: 45,
    description: "심폐 기능과 코어를 강화합니다.",
    instructions: ["플랭크 자세에서 시작합니다", "다리를 번갈아 가슴으로 가져옵니다", "빠르게 반복합니다"],
    calories: 10,
    youtubeVideoId: "nmwgirgXLYM",
  },
  {
    id: "running",
    name: "러닝",
    category: "cardio",
    difficulty: "beginner",
    muscleGroups: ["다리", "심폐"],
    sets: 1,
    reps: 1,
    duration: 30,
    restTime: 0,
    description: "심폐 기능을 향상시킵니다.",
    instructions: ["편안한 속도로 달립니다", "일정한 호흡을 유지합니다", "시간을 유지합니다"],
    calories: 15,
    youtubeVideoId: "gMEyMpMfwFE",
  },
  {
    id: "pull-up",
    name: "풀업",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["등", "이두근", "어깨"],
    sets: 3,
    reps: 8,
    restTime: 90,
    description: "상체 전체를 강화하는 맨몸 운동입니다.",
    instructions: ["철봉을 손가락 너비로 잡습니다", "턱이 철봉 위로 올라올 때까지 당깁니다", "천천히 내립니다"],
    calories: 12,
    youtubeVideoId: "eGo4IYlbE5g",
  },
  {
    id: "dumbbell-curl",
    name: "덤벨 컬",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["이두근"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "덤벨을 사용한 이두근 운동입니다.",
    instructions: ["덤벨을 양손에 잡고 섭니다", "팔꿈치를 구부려 올립니다", "천천히 내립니다"],
    calories: 7,
    youtubeVideoId: "ykJmroCEZH0",
  },
  {
    id: "triceps-pushdown",
    name: "트라이셉스 푸쉬다운",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["삼두근"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "삼두근을 강화합니다.",
    instructions: ["로프를 양손에 잡습니다", "팔꿈치를 구부려 내립니다", "천천히 올립니다"],
    calories: 8,
    youtubeVideoId: "2-LAMcv6Zus",
  },
  {
    id: "leg-raise",
    name: "레그 레이즈",
    category: "core",
    difficulty: "intermediate",
    muscleGroups: ["복부", "코어"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "하복부를 강화합니다.",
    instructions: ["누워서 다리를 펴고 있습니다", "다리를 들어올립니다", "천천히 내립니다"],
    calories: 8,
    youtubeVideoId: "JB2oyqG5Aso",
  },
  {
    id: "hip-stretch",
    name: "힙 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    muscleGroups: ["고관절", "대퇴사두근"],
    sets: 2,
    reps: 1,
    duration: 30,
    restTime: 15,
    description: "앉아있는 시간이 많은 현대인에게 필수적인 스트레칭입니다.",
    instructions: ["런지 자세로 앉습니다", "앞 무릎은 90도를 유지합니다", "뒷 무릎은 바닥에 닿게 합니다", "상체를 세우고 고관절을 앞으로 밀어줍니다", "자세를 유지합니다"],
    calories: 2,
    youtubeVideoId: "Ys-BNc2Sxcw",
  },
  // New gym equipment exercises
  {
    id: "bench-press",
    name: "벤치프레스",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["가슴", "삼두근", "어깨"],
    sets: 4,
    reps: 8,
    restTime: 90,
    description: "바벨을 사용한 상체 근력 운동입니다.",
    instructions: ["바벨을 어깨 높이에 잡습니다", "가슴으로 바벨을 내립니다", "팔을 펴서 위로 밀어올립니다"],
    calories: 15,
    youtubeVideoId: "rT7DgCr-3pg",
  },
  {
    id: "incline-bench-press",
    name: "인클라인 벤치프레스",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["상부 가슴", "어깨", "삼두근"],
    sets: 4,
    reps: 8,
    restTime: 90,
    description: "상부 가슴을 집중적으로 단련하는 운동입니다.",
    instructions: ["벤치를 45도 각도로 설정합니다", "바벨을 상부 가슴으로 내립니다", "팔을 펴서 올립니다"],
    calories: 14,
    youtubeVideoId: "SrqOu55AS9c",
  },
  {
    id: "dumbbell-press",
    name: "덤벨 프레스",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["가슴", "어깨", "삼두근"],
    sets: 4,
    reps: 10,
    restTime: 75,
    description: "덤벨을 사용한 가슴 운동입니다.",
    instructions: ["덤벨을 어깨 높이에 잡습니다", "가슴 위로 누릅니다", "천천히 내립니다"],
    calories: 12,
    youtubeVideoId: "QEQYIHm_G8E",
  },
  {
    id: "dumbbell-fly",
    name: "덤벨 플라이",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["가슴"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "가슴 내부를 집중적으로 단련합니다.",
    instructions: ["덤벨을 양손에 잡고 누워있습니다", "팔을 펼쳐 호를 그리며 내립니다", "천천히 올립니다"],
    calories: 10,
    youtubeVideoId: "eozdVT5CSPM",
  },
  {
    id: "chest-press",
    name: "체스트 프레스",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["가슴", "삼두근"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "머신을 사용한 가슴 운동입니다.",
    instructions: ["시트에 앉아 손잡이를 잡습니다", "가슴 높이에서 누릅니다", "천천히 돌아옵니다"],
    calories: 10,
    youtubeVideoId: "8DBYvIcqyWE",
  },
  {
    id: "pec-deck-fly",
    name: "펙덱 플라이",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["가슴"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "머신을 사용한 가슴 내부 운동입니다.",
    instructions: ["시트에 앉아 손잡이를 잡습니다", "팔을 모아 가슴 앞으로 가져옵니다", "천천히 펼칩니다"],
    calories: 9,
    youtubeVideoId: "VJDvDMWQw0E",
  },
  {
    id: "lat-pulldown",
    name: "랫풀다운",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["등", "이두근"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "등 근육을 강화하는 머신 운동입니다.",
    instructions: ["바를 어깨 너비로 잡습니다", "가슴으로 바를 당깁니다", "천천히 올립니다"],
    calories: 11,
    youtubeVideoId: "CAwf7n6Luuc",
  },
  {
    id: "seated-row",
    name: "시티드 로우",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["등", "이두근"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "등 중앙을 강화하는 머신 운동입니다.",
    instructions: ["시트에 앉아 손잡이를 잡습니다", "가슴으로 당깁니다", "천천히 돌아옵니다"],
    calories: 10,
    youtubeVideoId: "GZbfZ033f74",
  },
  {
    id: "barbell-row",
    name: "바벨 로우",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["등", "이두근", "코어"],
    sets: 4,
    reps: 8,
    restTime: 90,
    description: "등 전체를 강화하는 복합 운동입니다.",
    instructions: ["바벨을 무릎 높이에 잡습니다", "등을 곧게 펴고 당깁니다", "천천히 내립니다"],
    calories: 14,
    youtubeVideoId: "Syt3A25LXhk",
  },
  {
    id: "dumbbell-row",
    name: "덤벨 로우",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["등", "이두근"],
    sets: 3,
    reps: 10,
    restTime: 75,
    description: "한쪽 등 근육을 집중적으로 단련합니다.",
    instructions: ["덤벨을 한손에 잡고 무릎을 꿇습니다", "덤벨을 옆구리로 당깁니다", "천천히 내립니다"],
    calories: 11,
    youtubeVideoId: "pYcpY20QaFM",
  },
  {
    id: "leg-press",
    name: "레그프레스",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["대퇴사두근", "둔근", "햄스트링"],
    sets: 3,
    reps: 12,
    restTime: 75,
    description: "하체 전체를 강화하는 머신 운동입니다.",
    instructions: ["시트에 앉아 발판에 발을 올립니다", "다리를 펴서 밀어올립니다", "천천히 내립니다"],
    calories: 13,
    youtubeVideoId: "IZxyjW7MIAI",
  },
  {
    id: "leg-extension",
    name: "레그 익스텐션",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["대퇴사두근"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "허벅지 앞 근육을 집중적으로 단련합니다.",
    instructions: ["시트에 앉아 발목에 패드를 올립니다", "다리를 펴서 올립니다", "천천히 내립니다"],
    calories: 8,
    youtubeVideoId: "YyvSfVjQeL4",
  },
  {
    id: "leg-curl",
    name: "레그 컬",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["햄스트링"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "허벅지 뒤 근육을 강화합니다.",
    instructions: ["머신에 누워 발목에 패드를 올립니다", "다리를 구부려 올립니다", "천천히 내립니다"],
    calories: 8,
    youtubeVideoId: "1Dw9-ZL1XTA",
  },
  {
    id: "lunge",
    name: "런지",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["대퇴사두근", "둔근", "햄스트링"],
    sets: 3,
    reps: 10,
    restTime: 60,
    description: "한쪽 다리를 집중적으로 단련합니다.",
    instructions: ["한 발을 앞으로 내딛습니다", "앞 무릎이 90도가 될 때까지 내립니다", "원래 자세로 돌아옵니다"],
    calories: 10,
    youtubeVideoId: "Z2n58m1-TP4",
  },
  {
    id: "hip-thrust",
    name: "힙 쓰러스트",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["둔근", "햄스트링"],
    sets: 3,
    reps: 12,
    restTime: 75,
    description: "둔근을 집중적으로 강화합니다.",
    instructions: ["등을 벤치에 기대고 무릎을 구부립니다", "엉덩이를 위로 밀어올립니다", "천천히 내립니다"],
    calories: 12,
    youtubeVideoId: "wqzf3lFDVKk",
  },
  {
    id: "shoulder-press",
    name: "숄더 프레스",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["어깨", "삼두근"],
    sets: 3,
    reps: 10,
    restTime: 75,
    description: "어깨 근육을 강화하는 머신 운동입니다.",
    instructions: ["시트에 앉아 손잡이를 잡습니다", "위로 누릅니다", "천천히 내립니다"],
    calories: 11,
    youtubeVideoId: "qEwKCR5JCog",
  },
  {
    id: "overhead-press",
    name: "오버헤드 프레스",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["어깨", "삼두근", "가슴"],
    sets: 3,
    reps: 8,
    restTime: 90,
    description: "바벨을 사용한 어깨 운동입니다.",
    instructions: ["바벨을 어깨 높이에 잡습니다", "위로 누릅니다", "천천히 내립니다"],
    calories: 12,
    youtubeVideoId: "CnBmiBqp-AI",
  },
  {
    id: "lateral-raise",
    name: "레터럴 레이즈",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["어깨"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "옆 어깨를 강화합니다.",
    instructions: ["덤벨을 양손에 잡고 섭니다", "팔을 옆으로 들어올립니다", "천천히 내립니다"],
    calories: 8,
    youtubeVideoId: "3VczyxeIUw0",
  },
  {
    id: "front-raise",
    name: "프론트 레이즈",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["앞 어깨"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "앞 어깨를 강화합니다.",
    instructions: ["덤벨을 양손에 잡고 섭니다", "팔을 앞으로 들어올립니다", "천천히 내립니다"],
    calories: 8,
    youtubeVideoId: "LOKvVeer86s",
  },
  {
    id: "rear-delt-fly",
    name: "리어 델트 플라이",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["뒤 어깨"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "뒤 어깨를 강화합니다.",
    instructions: ["덤벨을 양손에 잡고 몸을 숙입니다", "팔을 옆으로 들어올립니다", "천천히 내립니다"],
    calories: 8,
    youtubeVideoId: "dD0Bx1yxO_E",
  },
  {
    id: "barbell-curl",
    name: "바벨 컬",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["이두근"],
    sets: 3,
    reps: 10,
    restTime: 60,
    description: "이두근을 강화합니다.",
    instructions: ["바벨을 양손에 잡고 섭니다", "팔꿈치를 구부려 올립니다", "천천히 내립니다"],
    calories: 8,
    youtubeVideoId: "kwG2ipFQSos",
  },
  {
    id: "hammer-curl",
    name: "해머 컬",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["이두근", "팔뚝"],
    sets: 3,
    reps: 12,
    restTime: 60,
    description: "이두근과 팔뚝을 강화합니다.",
    instructions: ["덤벨을 양손에 잡고 섭니다 (해머 그립)", "팔꿈치를 구부려 올립니다", "천천히 내립니다"],
    calories: 8,
    youtubeVideoId: "zC3nLlEvin4",
  },
  {
    id: "dips-machine",
    name: "딥스 (머신)",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["삼두근", "가슴"],
    sets: 3,
    reps: 10,
    restTime: 75,
    description: "머신을 사용한 딥스 운동입니다.",
    instructions: ["머신에 앉아 손잡이를 잡습니다", "팔을 펴서 내립니다", "천천히 올립니다"],
    calories: 10,
    youtubeVideoId: "6kALZisCUVE",
  },
  {
    id: "skull-crusher",
    name: "스컬 크러셔",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["삼두근"],
    sets: 3,
    reps: 10,
    restTime: 60,
    description: "삼두근을 집중적으로 단련합니다.",
    instructions: ["누워서 바벨을 가슴 위에 잡습니다", "팔꿈치를 구부려 이마 쪽으로 내립니다", "팔을 펴서 올립니다"],
    calories: 9,
    youtubeVideoId: "92IFaotsSqw",
  },
  // Bodyweight exercises
  {
    id: "chin-up",
    name: "친업",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["등", "이두근"],
    sets: 3,
    reps: 8,
    restTime: 90,
    description: "이두근을 강조한 풀업 변형입니다.",
    instructions: ["철봉을 손가락이 자신을 향하도록 잡습니다", "턱이 철봉 위로 올라올 때까지 당깁니다", "천천히 내립니다"],
    calories: 12,
    youtubeVideoId: "ARrKu9rAaxE",
  },
  {
    id: "dips-bodyweight",
    name: "딥스 (맨몸)",
    category: "strength",
    difficulty: "intermediate",
    muscleGroups: ["삼두근", "가슴"],
    sets: 3,
    reps: 8,
    restTime: 90,
    description: "맨몸으로 하는 딥스 운동입니다.",
    instructions: ["평행봉을 양손으로 잡습니다", "몸을 내립니다", "팔을 펴서 올립니다"],
    calories: 12,
    youtubeVideoId: "6kALZisCUVE",
  },
  {
    id: "bodyweight-squat",
    name: "맨몸 스쿼트",
    category: "strength",
    difficulty: "beginner",
    muscleGroups: ["대퇴사두근", "둔근"],
    sets: 3,
    reps: 15,
    restTime: 60,
    description: "장비 없이 하는 기본 스쿼트입니다.",
    instructions: ["발을 어깨 너비로 벌립니다", "무릎을 구부려 앉습니다", "일어섭니다"],
    calories: 8,
    youtubeVideoId: "aclHkVaku9U",
  },
  // Cardio exercises
  {
    id: "cycling",
    name: "사이클",
    category: "cardio",
    difficulty: "beginner",
    muscleGroups: ["다리", "심폐"],
    sets: 1,
    reps: 1,
    duration: 30,
    restTime: 0,
    description: "다리와 심폐를 강화합니다.",
    instructions: ["자전거에 앉습니다", "일정한 속도로 페달을 밟습니다", "시간을 유지합니다"],
    calories: 12,
    youtubeVideoId: "I_YIjfCNHT4",
  },
  {
    id: "jump-rope",
    name: "줄넘기",
    category: "cardio",
    difficulty: "intermediate",
    muscleGroups: ["다리", "팔", "심폐"],
    sets: 3,
    reps: 1,
    duration: 60,
    restTime: 30,
    description: "심폐 기능과 조정력을 향상시킵니다.",
    instructions: ["줄을 양손에 잡습니다", "일정한 속도로 뜁니다", "시간을 유지합니다"],
    calories: 16,
    youtubeVideoId: "6Xm6Ow8ynFg",
  },
  {
    id: "rowing",
    name: "로잉",
    category: "cardio",
    difficulty: "intermediate",
    muscleGroups: ["등", "다리", "팔", "심폐"],
    sets: 1,
    reps: 1,
    duration: 20,
    restTime: 0,
    description: "전신 심폐 운동입니다.",
    instructions: ["로잉 머신에 앉습니다", "일정한 리듬으로 노를 젓습니다", "시간을 유지합니다"],
    calories: 14,
    youtubeVideoId: "wqzf3lFDVKk",
  },
  {
    id: "stair-climber",
    name: "스텝퍼",
    category: "cardio",
    difficulty: "intermediate",
    muscleGroups: ["다리", "둔근", "심폐"],
    sets: 1,
    reps: 1,
    duration: 20,
    restTime: 0,
    description: "다리와 심폐를 강화합니다.",
    instructions: ["스텝퍼에 올라갑니다", "일정한 속도로 계단을 오릅니다", "시간을 유지합니다"],
    calories: 13,
    youtubeVideoId: "Y_QxKxVz9Ts",
  },
  {
    id: "hiit-training",
    name: "HIIT 훈련",
    category: "hiit",
    difficulty: "advanced",
    muscleGroups: ["전신"],
    sets: 8,
    reps: 1,
    duration: 30,
    restTime: 30,
    description: "고강도 인터벌 훈련입니다.",
    instructions: ["30초 동안 최대 강도로 운동합니다", "30초 휴식합니다", "반복합니다"],
    calories: 18,
    youtubeVideoId: "qmRnK9gF60w",
  },
  {
    id: "staircase",
    name: "천국의 계단",
    category: "cardio",
    difficulty: "advanced",
    muscleGroups: ["다리", "심폐"],
    sets: 1,
    reps: 1,
    duration: 10,
    restTime: 0,
    description: "극도의 고강도 다리 운동입니다.",
    instructions: ["계단을 빠르게 오릅니다", "내려갑니다", "반복합니다"],
    calories: 20,
    youtubeVideoId: "3B0g1fMj9Eo",
  },
];

export const WORKOUT_CATEGORIES = [
  { id: "strength", name: "근력 운동", icon: "dumbbell.fill", color: "#FF6B35", description: "근육 강화" },
  { id: "cardio", name: "유산소", icon: "figure.run", color: "#00D4AA", description: "심폐 기능" },
  { id: "hiit", name: "HIIT", icon: "bolt.fill", color: "#F59E0B", description: "고강도 인터벌" },
  { id: "yoga", name: "요가", icon: "waveform", color: "#8B5CF6", description: "유연성 & 마음" },
  { id: "stretching", name: "스트레칭", icon: "waveform", color: "#EC4899", description: "유연성 향상" },
  { id: "core", name: "코어", icon: "target", color: "#06B6D4", description: "코어 강화" },
] as const;

export function getExercisesByCategory(category: string): Exercise[] {
  return EXERCISES.filter((e) => e.category === category);
}

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}
